project_id = "rgzsdsqlqvrnjbnxkjjf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.cleanup-expired-bids]
verify_jwt = false

[functions.process-auctions]
verify_jwt = false